### ISSUE TITLE
feat: support custom `target: _blank` config for link

### ISSUE THREAD

**Issue by sanyuan0704** [sanyuan0704/island.js#102]
### Is your feature request related to a problem? Please describe.

Now Island.js set `target: _blank` for every external urls (start with `http://` or `https://`), but sometimes we don't want to open a new tab for some links.So we should improve the extensibility of this function.

### Describe the solution you'd like

For example, we can expose the config:

```ts
{
  markdown: {
    // The link in this list will not open a new window after click
    targetBlankWhiteList: []
  }
}
```

Now in Island.js，the `target: _blank` will be attached by `rehype-external-links`, so we can implement it through it.

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
Is there anyone who want to finish it?

**Comment by GODLiangCY** [comment]
I'm willing to give it a try in my spare time
