### ISSUE TITLE
feat: support check dead link

### ISSUE THREAD

**Issue by liuqh0609** [sanyuan0704/island.js#104]
### Is your feature request related to a problem? Please describe.

 Detect dead links  and give hints during the building process to avoid the problem of links not opening after going online.
eg:

![image](https://user-images.githubusercontent.com/43341115/196147965-be9913e5-ef5a-48e1-a2bf-cca504b0e4b2.png)

### Describe the solution you'd like

1. check internal link：by looking up the routing table
2. check external link:  the [`check-links`](https://www.npmjs.com/package/check-links) library is used to check whether the external links are properly accessible

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by liuqh0609** [comment]
Now there is a problem that the plugin is triggered to check for dead links every time a file is saved.
Do we need to add a cache to avoid repeated output messages?

**Comment by sanyuan0704** [comment]
In my point, it can be only triggered in production build

**Comment by liuqh0609** [comment]
> In my point, it can be only triggered in production build

Well maybe it should be. But now there are still two problems.
1. the detection of external links requires a network link, so there may be a delay in the results
2. does the dead link output information need to be printed uniformly after the build is completed?

**Comment by sanyuan0704** [comment]
On the one hand, the detect function should be options and user can close it by config.On the other hand, if the detect function enabled, then the ### detection should block the build process and exit once appearing dead link.

**Comment by liuqh0609** [comment]
ok, i think about what to do next

**Comment by liuqh0609** [comment]
TODO:
- [ ] Dead link cache to avoid secondary detection
