### ISSUE TITLE
feat: support image preview

### ISSUE THREAD

**Issue by liuqh0609** [sanyuan0704/island.js#106]
### Is your feature request related to a problem? Please describe.

Click on the image for preview.And support functions such as zooming in and out of images

### Describe the solution you'd like

No response

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
Awesome!

**Comment by Przeblysk** [comment]
Perfect features！！！
