### ISSUE TITLE
feat: responsive layout

### ISSUE THREAD

**Issue by sanyuan0704** [sanyuan0704/island.js#117]
### Is your feature request related to a problem? Please describe.

Now the default theme doesn't support responsive layout, which is necessary for mobile scene.

### Describe the solution you'd like

There are following parts should be finished:

- Mini navbar. For example:
![image](https://user-images.githubusercontent.com/39261479/198505585-67e6dce7-9130-4ce8-bf17-f0332dcfbc80.png)

- Mini sidebar: For example:

![image](https://user-images.githubusercontent.com/39261479/198505664-f50c65c0-8baf-4a6e-b0be-bf225dcd69cf.png)

- The sticky menu bar. For example:

![image](https://user-images.githubusercontent.com/39261479/198505797-a96a9b26-cc35-4ef0-abec-6ee58fe884bc.png)

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by spicylemonhaha** [comment]
Let me try

**Comment by spicylemonhaha** [comment]
https://github.com/sanyuan0704/island.js/commit/7aaaddbf049157bdfe45202d23e5863bb2609667
