### ISSUE TITLE
feat: more socialLinks

### ISSUE THREAD

**Issue by gumingWu** [sanyuan0704/island.js#120]
### Is your feature request related to a problem? Please describe.

support more socialLinks config, like juejin, twitter, even qrcode, and svg you want

### Describe the solution you'd like

more socialLinks supported

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
ok, it will be easier after we integrate iconify.
