### ISSUE TITLE
feat: backTop config

### ISSUE THREAD

**Issue by gumingWu** [sanyuan0704/island.js#121]
### Is your feature request related to a problem? Please describe.

Now, BackTop is a boolean config, maybe it can use object to have more control

### Describe the solution you'd like

backTop config

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
Good idea. What params do you think can be exposed?

**Comment by spicylemonhaha** [comment]
Maybe it can be these：
1. scrolling speed
2. position from the top of the browser after clicking the icon
3. icon customization
4. how far the page is from the top when the icon is displayed
5. etc.

**Comment by Flower-F** [comment]
> Maybe it can be these：
> 
> 1. scrolling speed
> 2. position from the top of the browser after clicking the icon
> 3. icon customization
> 4. how far the page is from the top when the icon is displayed
> 5. etc.

cool

**Comment by gumingWu** [comment]
> Good idea. What params do you think can be exposed?

animation, duration, and a BackTopDemo.tsx to show all animation

**Comment by sanyuan0704** [comment]
Now the backTop config can be put in @islandjs/plugin-backtop
