### ISSUE TITLE
Poor ux with search key

### ISSUE THREAD

**Issue by GODLiangCY** [sanyuan0704/island.js#129]
### Describe the bug

Now `island.js` supports to type `command + k` (or `ctrl + k`) to rouse the search component. However, many browsers also take this as their hot key.  And also because search component use `throttle` logic [here](https://github.com/sanyuan0704/island.js/blob/master/packages/plugin-search/src/component/index.tsx#L62-L98), these lead to a poor experience that if user type `ctrl + k` very quickly, search key will not work, browsers take over it instead,

Hence, can we reduce the throttle time or just remove throttle?

### Reproduction

See the official site of [`island.js`](https://island.sanyuan0704.top/en/)

### Expected behavior

Type `ctrl + k` can like immediately rouse the search component

### System Info

```Shell
System:
    OS: Linux 5.19 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 2.81 GB / 15.40 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Firefox: 104.0.2
  npmPackages:
    islandjs: workspace:* => 0.6.0
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
Thanks for your advice and i think it's neccessary to optimize the ux of search component.

**Comment by sanyuan0704** [comment]
The throttle logic could be removed~
