### ISSUE TITLE
docs: a translation mistake

### ISSUE THREAD

**Issue by leonnor** [sanyuan0704/island.js#150]
### Describe the bug

<img width="725" alt="image" src="https://user-images.githubusercontent.com/32327076/202180021-afb87c4b-a0e3-4a67-998c-06b04faacc16.png">

The word `SPA` means `单页应用程序`. It may confuse some new learners.

### Reproduction

None

### Expected behavior

None

### System Info

```Shell
None
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
Thanks
