### ISSUE TITLE
feat: create cli commands to initialize the project structure

### ISSUE THREAD

**Issue by inannan423** [sanyuan0704/island.js#165]
### Is your feature request related to a problem? Please describe.

For example, I want to create an island.js project that I can generate the project structure and default files with a single line of command instead of creating them one by one.

```bash
npx create-island@latest my-website
```

### Describe the solution you'd like

Create a CLI project and declare the commands in package.json：

```bash
{
  "name": "create-island",
  "version": "1.0.0",
  "bin": {
    "create-island": "./bin/create-island.js"
  }
}
```
Write logic in bin/index.js to complete the task.

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Shiinama** [comment]
🙋‍♂️

**Comment by inannan423** [comment]
cool! tks.👍
