### ISSUE TITLE
初始化项目+outDir

### ISSUE THREAD

**Issue by Yicoding** [sanyuan0704/island.js#169]
### Describe the bug

1.执行npx @islandjs/create-island@latest island-app失败
2.设置outDir没有生效
"islandjs": "^0.7.29"

### Reproduction

1.npx @islandjs/create-island@latest island-app

2.import { defineConfig } from "islandjs";

export default defineConfig({
  title: "my-site",
  outDir: "build",
});

### Expected behavior

1.执行npx @islandjs/create-island@latest island-app可以创建项目

2.设置outDir后生效

### System Info

```Shell
macos
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
Ok, i will check it.
