### ISSUE TITLE
support last updated feature

### ISSUE THREAD

**Issue by lweijian** [sanyuan0704/island.js#22]
### Is your feature request related to a problem? Please describe.

Now, island.js does not support last updated show in md ,like this
![image](https://user-images.githubusercontent.com/63062575/191160048-aa728d23-c417-470d-861d-0887d0ce2009.png)

### Describe the solution you'd like

use 'git log' to get the last updated timestamp

### Additional context

Now:
![image](https://user-images.githubusercontent.com/63062575/191160626-10fab379-ffa4-490e-a99b-cfcdab1617c4.png)

Expect:
![image](https://user-images.githubusercontent.com/63062575/191160729-cffd4d9c-e7b6-45e4-94c5-9c6d9ab20b4c.png)

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
How about implement it in remark plugin?

**Comment by sanyuan0704** [comment]
Howover, in this way we cannot get the markdown file path, cause that the git info of file cannot be found.So we perhaps look for other solutions.

**Comment by sanyuan0704** [comment]
Thank you for provide this feedback.I'll find the way to implement it, and welcome to pr for this feature🍻.

**Comment by sanyuan0704** [comment]
How about implement it in remark plugin? For example, add export const timestamp = xxx the compiled module code.Howover, in this way we cannot get the markdown file path, cause that the git info of file cannot be found.So we perhaps look for other solutions.

**Comment by lweijian** [comment]
> #43

Now, I'm dealing this with hmr, but I think my current practice is wrong
