### ISSUE TITLE
Cannot interact in Safari browser.

### ISSUE THREAD

**Issue by sanyuan0704** [sanyuan0704/island.js#33]
### Describe the bug

![image](https://user-images.githubusercontent.com/39261479/191883647-15039b62-7dce-49a9-a441-1f786572b4b4.png)

### Reproduction

Open the docs website in safari browser.

### Expected behavior

When we open the page, the aside marker and appearance button can be interactive.

### System Info

```Shell
-
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
The problem caused that island.js imports  react/react-dom by import map in production.But the compatibility is really poor, https://caniuse.com/?search=import%20map. And it cannot be support in all safari versions. Perherps we should inject some polyfill ahead to solve the problem, via https://github.com/guybedford/es-module-shims.

**Comment by lweijian** [comment]
I'm going to do it

**Comment by lweijian** [comment]
> I'm going to do it

https://github.com/sanyuan0704/island.js/pull/51

**Comment by sanyuan0704** [comment]
It's better to use `defer` because it will be sure that the polyfill is executed before app script, but async not.

**Comment by lweijian** [comment]
> It's better to use `defer` because it will be sure that the polyfill is executed before app script, but async not.

You're right. I've changed the code. Please review.
