### ISSUE TITLE
404 after clicking on the internal link in the official website document

### ISSUE THREAD

**Issue by liuqh0609** [sanyuan0704/island.js#39]
### Describe the bug

[document url](https://island.sanyuan0704.top/guide/spa-vs-mpa.html)
![image](https://user-images.githubusercontent.com/43341115/192455764-3686f74b-f512-4d03-8289-8701f4e417f0.png)

The address in the documentation is `. /islands-arch`, so the jump fails. Do I need to change it to `. /guide/islands-arch`?
And I checked the code, in the `remarkPluginNormalizeLink` file `node.url = path.join(base, url)` is written like this, do I need to recognize the path where the file itself is located to splice, instead of using base directly?

I'm also confused about which is the correct way. ^^

### Reproduction

1. Click on the internal links in the document

### Expected behavior

Correct page jumping

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 834.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 16.0
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
I think it's better to change the url to `/guide/islands-arch`

**Comment by liuqh0609** [comment]
> I think it's better to change the url to `/guide/islands-arch`

ok

**Comment by codersjj** [comment]
The [documentation](https://islandjs.dev/en/api/config-basic#base) says the default value of `base` is `/`, but if I don't explicitly set it, the default value of `base` doesn't seem to be `/`, and the button `Take me home` also doesn't work.

![take-me-home](https://github.com/sanyuan0704/island.js/assets/44868357/3bb16615-70e2-43ba-bf5a-c0089b5d8290)
