### ISSUE TITLE
some text is not localized in Chinese site mode

### ISSUE THREAD

**Issue by liuqh0609** [sanyuan0704/island.js#47]
### Describe the bug

some text is not localized in Chinese site mode,perhaps because the relevant adaptations are not done.
<img width="820" alt="image" src="https://user-images.githubusercontent.com/43341115/193392730-a051e777-6a84-4b4a-ae22-7b32b7e04168.png">
<img width="209" alt="image" src="https://user-images.githubusercontent.com/43341115/193392737-16e091ad-a7fd-43f4-b0dd-484e62290fe5.png">

### Reproduction

1. Open the offical [website](https://island.sanyuan0704.top/zh/guide/configure-site.html)

### Expected behavior

Proper display of configured localized text

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 120.80 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.61
    Safari: 16.0
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
I think the `themeCofig.locales` could expose more params such as lastUpdatedText、prevPage、nextPage to support different language  in these areas.

**Comment by liuqh0609** [comment]
yep, I think so too, I mentioned a pr
