### ISSUE TITLE
E2e test needed in this project

### ISSUE THREAD

**Issue by sanyuan0704** [sanyuan0704/island.js#50]
### Is your feature request related to a problem? Please describe.

Without e2e test case, we may dismiss some edge case and have some potential risk before publishing the package, e.g. #49 

### Describe the solution you'd like

The e2e test will base on Vitest and playwright, referenced vitepress implement. https://github.com/vuejs/vitepress/pull/1012

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by STDSuperman** [comment]
Maybe I can do this.

**Comment by STDSuperman** [comment]
> Maybe I can do this.

If I don't submit a pr today, I give up🤡.

**Comment by sanyuan0704** [comment]
> > Maybe I can do this.
> 
> If I don't submit a pr today, I give up🤡.

hh, welcome to pr, but it has a little bit complexity,so we can do it in a long way

**Comment by linbudu599** [comment]
@sanyuan0704 这是我的同事hhh
@STDSuperman 酱紫写
