### ISSUE TITLE
Without initializing the git repository, the program terminates directly

### ISSUE THREAD

**Issue by liuqh0609** [sanyuan0704/island.js#55]
### Describe the bug

According to the official documentation, when initializing the project, when the git repository is not initialized, the execution dev will throw an error directly and the page will not be displayed properly.
<img width="893" alt="image" src="https://user-images.githubusercontent.com/43341115/193437101-4f047e11-b74b-4b06-bbfa-09c80268c212.png">

### Reproduction

1. Quick start to initialize the project with the  [official documentation](https://island.sanyuan0704.top/en/guide/getting-started.html)
2. Execute `pnpm run dev`

### Expected behavior

Correctly display the startup page

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 137.02 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.91
    Safari: 16.0
  npmPackages:
    islandjs: ^0.2.4 => 0.2.4
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by liuqh0609** [comment]
I tried to fix it.🧐

**Comment by liuqh0609** [comment]
#56

**Comment by liuqh0609** [comment]
But I'm not quite sure if the default date displayed can be used with now()

**Comment by sanyuan0704** [comment]
I think it's ok to use now() as fallback value
