### ISSUE TITLE
Home page hmr doesn't work

### ISSUE THREAD

**Issue by sanyuan0704** [sanyuan0704/island.js#65]
### Describe the bug

When i change the home page front matter, such as:

```md
// index.md
---
pageType: 'home'

hero:
  text: Island
  ...
---
```
The change cannot be applied in home component unless i reload the page manually.

### Reproduction

See details in above.

### Expected behavior

When i change the markdown for homepage, the hmr will work normally.

### System Info

```Shell
-
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
Is there anyone who wants to solve the problem?

**Comment by liuqh0609** [comment]
Maybe I can try
