### ISSUE TITLE
Cli command params support

### ISSUE THREAD

**Issue by sanyuan0704** [sanyuan0704/island.js#70]
### Is your feature request related to a problem? Please describe.

Currently, Island.js has a cli  but it doesn't support inline params,  such as `island dev docs --port=8080`.

### Describe the solution you'd like

Support cli inline params and pass on the params to `Vite`.

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
Is there anyone who wants to try this?

**Comment by spicylemonhaha** [comment]
Shall I give it a try？If I don't PR within five days, I'll give up.

**Comment by sanyuan0704** [comment]
OK



---Original---
From: ***@***.***&gt;
Date: Wed, Oct 19, 2022 09:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sanyuan0704/island.js] Cli command params support (Issue #70)




 
Shall I give it a try？If I don't PR within five days, I'll give up.

**Comment by spicylemonhaha** [comment]
Thanks, if I can do it, I will pull the request before the 23rd

**Comment by sanyuan0704** [comment]
TODO: cli params for build and preview command

**Comment by sanyuan0704** [comment]
#109

**Comment by spicylemonhaha** [comment]
Thank you for merging, I will continue to follow up on this issue🎈

**Comment by spicylemonhaha** [comment]
https://github.com/sanyuan0704/island.js/pull/113
