### ISSUE TITLE
Server restart automatically after adding new markdown file

### ISSUE THREAD

**Issue by Flower-F** [sanyuan0704/island.js#75]
### Is your feature request related to a problem? Please describe.

If we want to add a new markdown file, we must run the `pnpm dev` again to restart the server in order to load the new page, or we will get a 404 page.

### Describe the solution you'd like

After adding the new page, the server will automatically restart, and we don't need to run the `pnpm dev` by ourselves.

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
It' a little confused because when i add markdown in islandjs docs directory the server can automatically update the module graph as well as route object.But in a outside demo it cannot work.

**Comment by sanyuan0704** [comment]
I figure out the cause.Because the `config.root` passed to vite is always the islandjs path, so vite cannot watch the user dir.As the result, we should listen the user dir by `chokidar` manually.

```ts
// src/node/plugin-routes/index.ts
    server.watcher
      .on('add', async (file) => {
        // ...
      })
      .on('unlink', async (file) => {
        // ...
      });
```

So `server.watcher` should be our `chokidar` that watches the user root dir.

**Comment by sanyuan0704** [comment]
@Flower-F  Are you interested in implementing it?

**Comment by Flower-F** [comment]
> It' a little confused because when i add markdown in islandjs docs directory the server can automatically update the module graph as well as route object.But in a outside demo it cannot work.

Yes, it's so confused.
