### ISSUE TITLE
Build and test failed in Windows System

### ISSUE THREAD

**Issue by Flower-F** [sanyuan0704/island.js#80]
### Describe the bug

Because of the path difference of Windows and Mac, the test will failed because it got a different path starts with something like "D:", and it will contains a lot of backslash(\\). Both of them cause the babelPluginIsland can't work well.
![image](https://user-images.githubusercontent.com/78215016/194901403-364b0258-6881-4fff-8499-26ad552ed331.png)

To build the project, there will also be some problems.
![image](https://user-images.githubusercontent.com/78215016/194902169-e35d65f0-d030-48ee-843b-77d1de1022c9.png)
I tried to solve it by adding the `pathToFileURL` function, and it solve the dynamic import problem.
![image](https://user-images.githubusercontent.com/78215016/194902884-1f97430e-775a-4e7d-9f6c-395a939492bd.png)
But as I mention above in the test, the build still failed because of the difference path of Windows.

Of cause we often deploy project in Unix/Linux System, so we might not need to support Windows System. But I think that if we can support it, the Windows users can also preview the production in local environment. And that's great. Or we might need to give some warnings to the users in the docs.

### Reproduction

A basic island project.

### Expected behavior

Build and test normally.

### System Info

```Shell
Windows System
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
Ok, i'll solve the potential problem in window.

**Comment by sanyuan0704** [comment]
https://github.com/sanyuan0704/island.js/pull/93

**Comment by Flower-F** [comment]
> #93

Cool
