### ISSUE TITLE
Is there any way to inject global style？

### ISSUE THREAD

**Issue by Hitsuki9** [sanyuan0704/island.js#85]
### Is your feature request related to a problem? Please describe.

For example, if I want to use KaTex, the `katex.css` should be linked on each page, Otherwise, the formula will not render correctly.

### Describe the solution you'd like

Maybe supporting template HTML file is one of the solutions.

### Validations

- [x] Read the [docs](https://island.sanyuan0704.top).
- [X] Read the [Contributing Guidelines](https://github.com/sanyuan0704/island/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
Now you can only put it in custom theme directory, refer https://github.com/sanyuan0704/island-tutorial/tree/master/docs/.island. But i will open a pr to add the interface later.

**Comment by sanyuan0704** [comment]
@Hitsuki9

**Comment by Hitsuki9** [comment]
Thanks, it works. Expect the release of custom theme.

**Comment by sanyuan0704** [comment]
Custom theme has been released in v0.4, doc: https://island.sanyuan0704.top/zh/guide/custom-theme.html

**Comment by Hitsuki9** [comment]
> Custom theme has been released in v0.4, doc: https://island.sanyuan0704.top/zh/guide/custom-theme.html

Cool
